What seems to work?
* PB Thresholding on input.
* Loop over buffers - using zip pairs or t+1 ~(zipped pairs maybe better for custom pairings).

What needs adjusting?
* What exactly the outputs and inputs are? Binary signals or probabilities? Subtracted feedback or something else?


In [6]:
from src.var_processor.pb_threshold import pb_threshold
import numpy as np

In [102]:
def check_size(self, frame):
    """Check size of input matches array shape."""
    if frame.shape == self.forward_array.shape[0:2]:
        return True
    else:
        return False

def add_to_array(array, frame):
    """Add a frame to a rolling array."""
    array = np.roll(array, -1, axis=2)
    # Add frame to end of buffer
    array[..., -1] = frame
    return array

def process_array(array):
    """Process an array."""
    # Start with just averaging - could be convolution
    return np.mean(array, axis=2)


class Buffer:
    """Object for a time buffer."""

    def __init__(self, rows, cols, length):
        """Initialise object.

        Assumes 8-bit values (for now).
        """
        # Set up an array to store a rolling window of inputs
        self.forward_array = np.zeros(shape=(rows, cols, length), dtype=np.uint8)
        # Initialise feedback mean
        self.backward_array = np.zeros(shape=(rows, cols, length), dtype=np.uint8)  

    def feedforward(self, frame):
        """Add a frame to the buffer in FF mode."""
        self.forward_array = add_to_array(self.forward_array, frame)
        return None
    
    def feedback(self, frame):
        """Add a frame to the buffer in FB mode."""
        self.backward_array = add_to_array(self.backward_array, frame)
        return None

    @property
    def latest(self):
        """Return latest entry in buffer."""
        return self.forward_array[..., -1]
    
    @property
    def ff_output(self):
        """Provide feedforward output."""
        average = process_array(self.forward_array)
        # Convert to 8-bit for thresholding
        converted = (average*255).astype(np.uint8)
        # Add non-linearity
        binary = pb_threshold(converted)
        return binary
        
    @property
    def fb_output(self):
        """Provide feedback / reconstruction output."""
        average = process_array(self.backward_array)
        # Subtract input - this is just the latest frame
        # Need to delete average from latest as average is likely to be < latest?
        difference = self.latest - average  # This is float64
        # Clip to 0 to 1
        clipped = np.clip(difference, 0, 1)
        # Convert to 8-bit integer
        converted = (clipped*255).astype(np.uint8)
        # Add non-linearity
        binary = pb_threshold(converted)
        return binary
        
    def iterate(self, input_frame, input_feedback):
        """Perform both a forward and backward pass."""
        self.feedforward(input_frame)
        self.feedback(input_feedback)
        return self.ff_output, self.fb_output


In [103]:
b = Buffer(4, 1, 2)
a = np.arange(0, 4).reshape(4, 1)
b.feedforward(a)
assert np.array_equal(b.latest, a)
b.feedforward(a)
assert np.array_equal(b.latest, a)
b.feedforward(a)
assert np.array_equal(b.latest, a)
average = b.ff_output
assert average.shape == a.shape
assert average.max() <= 1
assert average.min() >= 0
b.feedback(a)
fb_output = b.fb_output
assert fb_output.shape == a.shape
assert fb_output.max() <= 1
assert fb_output.min() >= 0

How do we do the pb_threshold with float64 data representing the difference?

Average has a maximum of 1 and fb has a max of 1 so the range is -1 > 1. Ah so we times by 128 and add 128 to get 8-bit values? But would this affect the suppression of values less than 0?

Do we want instead to clip the negative values to 0 then scale? No - if we just times by 255 this will happen as values less than 0 will be clipped? but then we would have a range of -255 to 255 > 8 bit. And if our positive values stop at 128 then they'd be compared with 255 values...

So we need to clip then times by 255 then threshold as 8-bit values?

In [104]:
self = b
average = process_array(self.forward_array)

In [105]:
average

array([[0.],
       [1.],
       [2.],
       [3.]])

In [106]:
self.forward_array

array([[[0, 0]],

       [[1, 1]],

       [[2, 2]],

       [[3, 3]]], dtype=uint8)

In [107]:
print(average.dtype)

float64


In [108]:
data_type = average.dtype
bit_size = data_type.itemsize*8; print(bit_size)

64


In [109]:
data_type.itemsize

8

In [110]:
self.forward_array.dtype.itemsize

1

In [111]:
# Subtract input - this is just the latest frame
difference = average - self.latest  # This is float64
# Clip to 0 to 1
clipped = np.clip(difference, 0, 1)
# Convert to 8-bit integer
converted = (clipped*255).astype(np.uint8)
# Add non-linearity
binary = pb_threshold(converted)
print(difference, clipped, converted, binary)

[[0.]
 [0.]
 [0.]
 [0.]] [[0.]
 [0.]
 [0.]
 [0.]] [[0]
 [0]
 [0]
 [0]] [[0]
 [0]
 [0]
 [0]]


In [112]:
b = Buffer(4, 1, 2)

In [113]:
a = np.random.randint(255, size=(4,1)); print(a)
b.feedforward(a)
assert np.array_equal(b.latest, a)
b.feedforward(a)
assert np.array_equal(b.latest, a)
b.feedforward(a)
assert np.array_equal(b.latest, a)
average = b.ff_output
assert average.shape == a.shape
assert average.max() <= 1
assert average.min() >= 0
b.feedback(a)
fb_output = b.fb_output
assert fb_output.shape == a.shape
assert fb_output.max() <= 1
assert fb_output.min() >= 0

[[103]
 [ 76]
 [224]
 [229]]


In [114]:
print(average, fb_output)

[[1]
 [1]
 [0]
 [0]] [[1]
 [1]
 [1]
 [1]]


# Connecting the Buffers Together

Our time series objects don't need to have any flags or counts with the buffer above.

We look at the averaging as a form of reversable down and up sampling - which just equates to an integrator followed by a threshold.

So we convert binary pulses into a fraction representing the average frequency, which is also an estimate of the intensity in a set range (e.g. 8 bit), then we convert that into a binary pulse.

In [115]:
base_list = range(0,5)
print([i for i in base_list])
for e1, e2 in zip(base_list[:-1], base_list[1:]):
    print(e1, e2)

[0, 1, 2, 3, 4]
0 1
1 2
2 3
3 4


In [188]:
class TimeSeries:
    """Generate a cascade of time buffers."""

    def __init__(self, rows, cols, length, stages):
        """Initialise list for buffer series.
        
        Args:
            rows - integer indicating input array (frame) height in rows.
            cols - integer indicating input array (frame) width in cols.
            length - integer indicating number of time steps to buffer.
            stages - integer indicating the number of buffer stages.
        """
        self.time_series = list()
        self.shape = (rows, cols, length)
        # Generate series of buffers
        self.time_series = [Buffer(*self.shape) for i in range(0, stages)]
        return None

    def add(self, frame):
        """Add frame for processing.
        
        This runs for each time iteration and passes information between buffers.
        """
        # Define variable to hold data passed forward 
        feedforward = frame
        # Iterate through pairs of buffers in series 
        for buffer_ff, buffer_fb in zip(self.time_series[:-1], self.time_series[1:]):
            feedback = buffer_fb.fb_output
            # Get feedforward and feedback for buffer
            feedforward, feedback = buffer_ff.iterate(feedforward, feedback)
        # Then feedforward to last buffer
        self.time_series[-1].iterate(feedforward, feedback)
        return None
    
    @property
    def ff_output(self):
        """Provide feedforward output of all arrays."""
        return np.asarray([buffer.ff_output for buffer in self.time_series]) 
        
    @property
    def fb_output(self):
        """Provide feedback / reconstruction output."""
        return np.asarray([buffer.fb_output for buffer in self.time_series]) 

    @property
    def latest(self):
        """Get last entry of each buffer as array."""
        return np.asarray([buffer.latest for buffer in self.time_series]) 
    
    def __repr__(self):
        """Output a string representation."""
        string_list = [
            "FF", np.array_repr(self.ff_output), "---", 
            "FB", np.array_repr(self.fb_output), "---", 
            "Latest", np.array_repr(self.latest), "---"]
        return "\n\n".join(string_list)
    
    def reconstruct(self, time_periods):
        """Reconstruct an input.
        
        Arg:
            time_periods - integer indicating no. of outputs to sum 
        """
        buffer_sum = np.asarray([self.fb_output for i in range(0, time_periods)])
        

In [189]:
ts = TimeSeries(4,3,6,8)

So this creates 8 buffers in series that take a 2D input of 4 rows and 3 columns and are adapted to store 6 samples.

In [190]:
print(ts)

FF

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

---

FB

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 

In [191]:
ts.ff_output.shape

(8, 4, 3)

In [192]:
def test_timeseries():
    """Test the time series object."""
    ts = TimeSeries(4,3,6,8)
    # Check everything is initialised to 0
    assert np.array_equal(ts.ff_output, np.zeros((8, 4,3)))
    assert np.array_equal(ts.fb_output, np.zeros((8, 4,3)))
    assert np.array_equal(ts.latest, np.zeros((8, 4,3)))
    a = np.random.randint(255, size=(4,3), dtype=np.uint8)
    pb_a = pb_threshold(a)
    ts.add(pb_a)

In [193]:
a = np.arange(0, 4, dtype=np.uint8); print(a)
b = a.reshape(1,1,-1); print(b.shape)
process_array(b)

[0 1 2 3]
(1, 1, 4)


array([[1.5]])

In [194]:
def test_processarray():
    """Test process array function."""
    a = np.arange(0, 4, dtype=np.uint8); 
    b = a.reshape(1,1,-1); 
    assert process_array(b) == 1.5

In [195]:
test_processarray()

In [196]:
test_timeseries()

In [197]:
a = np.random.randint(255, size=(4,3), dtype=np.uint8)
pb_a = pb_threshold(a)
ts.add(pb_a)

In [198]:
print(ts)

FF

array([[[0, 0, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

---

FB

array([[[1, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 

In [199]:
for i in range(0, 100):
    a = np.random.randint(255, size=(4,3), dtype=np.uint8)
    pb_a = pb_threshold(a)
    ts.add(pb_a)
    print(ts)

FF

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1],
        [1, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

---

FB

array([[[1, 1, 0],
        [1, 1, 1],
        [1, 0, 1],
        [0, 1, 0]],

       [[1, 1, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 

FF

array([[[0, 0, 1],
        [1, 0, 1],
        [0, 1, 1],
        [1, 1, 0]],

       [[0, 1, 0],
        [1, 1, 0],
        [1, 1, 0],
        [1, 1, 0]],

       [[1, 1, 0],
        [1, 0, 1],
        [0, 1, 0],
        [1, 0, 0]],

       [[1, 0, 1],
        [1, 1, 0],
        [0, 1, 0],
        [0, 1, 0]],

       [[1, 0, 0],
        [1, 1, 1],
        [1, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [0, 0, 1],
        [0, 0, 0],
        [1, 1, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0],
        [1, 0, 0]],

       [[1, 0, 0],
        [0, 0, 1],
        [1, 1, 0],
        [1, 1, 0]]])

---

FB

array([[[0, 1, 1],
        [1, 1, 1],
        [0, 0, 0],
        [1, 0, 0]],

       [[0, 0, 0],
        [0, 1, 0],
        [1, 1, 1],
        [1, 1, 0]],

       [[0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
        [0, 0, 1]],

       [[0, 0, 1],
        [1, 0, 0],
        [1, 1, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 0],
        [1, 

FF

array([[[0, 1, 1],
        [0, 0, 1],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 1, 0],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 1, 1],
        [1, 1, 0],
        [0, 1, 0],
        [0, 1, 0]],

       [[0, 1, 0],
        [1, 1, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 1, 0],
        [1, 1, 1],
        [0, 1, 0],
        [1, 1, 0]],

       [[1, 1, 0],
        [0, 1, 1],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 1, 0],
        [0, 1, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [1, 1, 1],
        [0, 0, 1],
        [0, 0, 1]]])

---

FB

array([[[1, 0, 1],
        [0, 1, 1],
        [1, 1, 0],
        [0, 1, 1]],

       [[1, 0, 0],
        [1, 1, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 1],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 1],
        [1, 1, 0],
        [0, 0, 1],
        [1, 0, 0]],

       [[0, 0, 1],
        [1, 0, 1],
        [0, 

In [168]:
print(ts)

FF

array([[[0, 1, 0],
        [0, 1, 1],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 1, 0],
        [0, 0, 0],
        [1, 1, 0],
        [1, 0, 1]],

       [[0, 1, 1],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0]],

       [[0, 0, 1],
        [0, 1, 0],
        [1, 1, 1],
        [1, 0, 1]],

       [[0, 1, 1],
        [0, 1, 1],
        [0, 1, 1],
        [0, 1, 0]],

       [[1, 0, 1],
        [0, 0, 1],
        [0, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [0, 0, 1],
        [1, 1, 0],
        [1, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

---

FB

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 0, 0]],

       [[1, 1, 0],
        [0, 1, 0],
        [0, 1, 1],
        [1, 0, 0]],

       [[1, 0, 0],
        [0, 0, 0],
        [1, 0, 0],
        [1, 0, 0]],

       [[0, 0, 1],
        [0, 0, 1],
        [0, 

Feedback output is always 0. Is this because the data is random and there are no patterns? Or because a bug in the clipping code?

In [160]:
print(ts.time_series[0].forward_array.shape, ts.time_series[0].forward_array, sep="\n\n")

(4, 3, 6)

[[[1 1 0 1 0 1]
  [0 1 0 1 0 0]
  [1 1 0 1 1 0]]

 [[0 0 1 0 0 1]
  [1 1 0 1 0 1]
  [1 1 1 1 0 0]]

 [[0 1 1 0 1 0]
  [1 0 0 1 1 1]
  [0 0 1 0 0 1]]

 [[1 1 0 1 0 0]
  [0 1 0 1 1 0]
  [1 1 1 0 0 0]]]


In [161]:
process_array(ts.time_series[0].forward_array)

array([[0.66666667, 0.33333333, 0.66666667],
       [0.33333333, 0.66666667, 0.66666667],
       [0.5       , 0.66666667, 0.33333333],
       [0.5       , 0.5       , 0.5       ]])

In [162]:
for i in range(0,6):
    print(ts.time_series[0].forward_array[:,:, i])

[[1 0 1]
 [0 1 1]
 [0 1 0]
 [1 0 1]]
[[1 1 1]
 [0 1 1]
 [1 0 0]
 [1 1 1]]
[[0 0 0]
 [1 0 1]
 [1 0 1]
 [0 0 1]]
[[1 1 1]
 [0 1 1]
 [0 1 0]
 [1 1 0]]
[[0 0 1]
 [0 0 0]
 [1 1 0]
 [0 1 0]]
[[1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 0]]


### Now Check Backward Array

In [163]:
for i in range(0,6):
    print(ts.time_series[0].backward_array[:,:, i])

[[0 0 0]
 [0 1 1]
 [0 0 0]
 [0 0 1]]
[[0 0 0]
 [0 0 1]
 [0 0 0]
 [1 0 0]]
[[1 1 1]
 [0 1 1]
 [0 1 0]
 [1 0 1]]
[[1 1 1]
 [0 1 0]
 [0 0 0]
 [1 0 1]]
[[0 1 1]
 [0 0 1]
 [0 0 0]
 [0 1 0]]
[[0 0 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]]


In [164]:
process_array(ts.time_series[0].backward_array)

array([[0.33333333, 0.5       , 0.66666667],
       [0.16666667, 0.5       , 0.83333333],
       [0.        , 0.33333333, 0.        ],
       [0.66666667, 0.16666667, 0.5       ]])

In [165]:
ts.time_series[0].latest - process_array(ts.time_series[0].backward_array)

array([[ 0.66666667, -0.5       , -0.66666667],
       [ 0.83333333,  0.5       , -0.83333333],
       [ 0.        ,  0.66666667,  1.        ],
       [-0.66666667, -0.16666667, -0.5       ]])

In [166]:
np.clip(ts.time_series[0].latest - process_array(ts.time_series[0].backward_array), 0, 1)

array([[0.66666667, 0.        , 0.        ],
       [0.83333333, 0.5       , 0.        ],
       [0.        , 0.66666667, 1.        ],
       [0.        , 0.        , 0.        ]])

In [182]:
self = ts
time_periods = 32
buffer_sum = np.asarray([self.fb_output for i in range(0, time_periods)])

In [184]:
buffer_sum.shape

(32, 8, 4, 3)

In [186]:
summed = buffer_sum.sum(axis=0)
print(summed, summed.shape)

[[[32  0 20]
  [19  0 32]
  [ 0  0 17]
  [23  0  0]]

 [[ 0  0 13]
  [21  0 20]
  [ 0 28  0]
  [32  0  0]]

 [[ 0  0  0]
  [28  0 16]
  [ 0  0 14]
  [32  0  0]]

 [[ 0  0  8]
  [20 22 13]
  [ 0 21  0]
  [ 0  0  0]]

 [[ 0  0 12]
  [32 18  0]
  [31 32 28]
  [22  0  0]]

 [[ 0  0 12]
  [ 0  0  3]
  [32  0  0]
  [10 19  0]]

 [[ 0  0 26]
  [ 0  0 32]
  [ 0 20  0]
  [16  0 32]]

 [[ 0  0 12]
  [14  0  9]
  [ 0  0  0]
  [29  0  0]]] (8, 4, 3)


Ah. We have several high values for common elements - we will get sums higher than 32. Surely that is not right?

Is any useful information being stored and transmitted or is it all being lost due to the PB threshold on the output?

We could do with a visualisation - we can look at a single pulse train. To see properly, we have a time base that is X times the actual time base so we can insert blanks then we draw single lines - https://stackoverflow.com/questions/44951911/plot-a-binary-timeline-in-matplotlib. We can start from our eigenvalue calculation.

In [200]:
ts = TimeSeries(1,1,6,8)

In [204]:
ff = ts.ff_output; fb = ts.fb_output

In [205]:
print(ff.shape, fb.shape)

(8, 1, 1) (8, 1, 1)


In [206]:
ff

array([[[0]],

       [[0]],

       [[0]],

       [[0]],

       [[0]],

       [[0]],

       [[0]],

       [[0]]])

In [209]:
ff.reshape(8).shape

(8,)

In [208]:
fb

array([[[0]],

       [[0]],

       [[0]],

       [[0]],

       [[0]],

       [[0]],

       [[0]],

       [[0]]])