In this notebook, we'll look at building a visualiser to view the VPU applied en-mass to FFT data.

We can make our SensorSource objects iterables that return a next frame of data - https://www.programiz.com/python-programming/iterator ```__iter__``` just returns self (with any initialisation) and ```__next__``` returns self.read().

Our SensorSource objects also need a way of returning the size of the frame.

# Testing Sensor Sources

In [1]:
from src.sources.capture import VideoSource

video = VideoSource()
video.start()
grabbed, frame = video.read()
print(grabbed)
print(frame.shape)

video.stop()

True
(480, 640, 3)


In [2]:
from src.sources.capture import AudioSource
import time
import numpy as np

audio = AudioSource()
audio.start()
time.sleep(0.5)
# Test read
length1, samples1 = audio.read()
assert length1
assert samples1.any()
# Check starting and getting a frame
audio.start()
time.sleep(0.5)
length2, samples2 = audio.read()
assert length2
assert not np.array_equal(samples1, samples2)
print(samples2.shape)
# Test stopping
audio.stop()
assert not audio.started

[!] Asynchroneous capturing has already been started.
(65536,)


In [3]:
from src.sources.capture import CombinedSource, SensorSource

combined = CombinedSource()
type(combined.sources) == dict

True

In [4]:
len(combined.sources)

0

In [5]:
assert type(combined.sources) == dict
assert len(combined.sources) == 0
# Adding a source
combined.add_source(SensorSource())

In [6]:
list(combined.sources.items())[0][0]

'SensorSource'

In [7]:
from src.sources.capture import AVCapture

av = AVCapture()
av.start()
time.sleep(0.25)
data = av.read()
print(data)
av.stop()

{'audio': array([    0,     0,     0, ...,  9282, 11614, 11899], dtype=int16), 'video': array([[[168, 166, 125],
        [168, 166, 125],
        [169, 163, 125],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[170, 164, 127],
        [170, 164, 127],
        [169, 163, 125],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[170, 164, 127],
        [169, 163, 125],
        [169, 163, 125],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[114, 104,  80],
        [114, 104,  80],
        [114, 103,  82],
        ...,
        [103,  88,  91],
        [101,  90,  88],
        [101,  90,  88]],

       [[114, 104,  80],
        [113, 102,  79],
        [113, 102,  81],
        ...,
        [104,  90,  92],
        [101,  91,  86],
        [102,  92,  87]],

       [[115, 105,  73],
        [115, 105,  73],
        [112, 104,  73],

# Test Covariance Unit

In [8]:
from src.var_processor.covariance import CovarianceUnit
cov_unit = CovarianceUnit(2)
print(cov_unit.x_sum, cov_unit.square_sum, cov_unit.covariance, sep="\n", end="\n---\n")
assert not cov_unit.x_sum.any()
assert not cov_unit.square_sum.any()
# Test updating with data
ones = np.ones(shape=(2,1))
cov_unit.update(ones)
assert cov_unit.count == 1
assert np.array_equal(cov_unit.x_sum, ones)
assert np.array_equal(cov_unit.mean, ones)
assert not cov_unit.covariance.any()
print(cov_unit.x_sum, cov_unit.square_sum, cov_unit.covariance, sep="\n", end="\n---\n")
threes = ones*3
cov_unit.update(threes)
assert cov_unit.count == 2
assert np.array_equal(cov_unit.x_sum, ones+threes)
assert cov_unit.square_sum.any()
assert np.array_equal(cov_unit.mean, ones*2)
assert cov_unit.covariance.any()
print(cov_unit.x_sum, cov_unit.square_sum, cov_unit.covariance, sep="\n", end="\n---\n")

[[0.]
 [0.]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
---
[[1.]
 [1.]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
---
[[4.]
 [4.]]
[[0.66666667 0.66666667]
 [0.66666667 0.66666667]]
[[0.33333333 0.33333333]
 [0.33333333 0.33333333]]
---


In [9]:
from src.var_processor.power_iterator import PowerIterator

power = PowerIterator(2)
power.ev

array([[0.86279936],
       [0.5055465 ]])

In [10]:
from src.var_processor.vpu import VPU

# Intialise VPU
vpu = VPU(2)
# Test Iteration
in_1 = np.random.randint(255, size=(2, 1))
in_1 = in_1 / in_1.max()
print(in_1)
r, residual = vpu.iterate(in_1)
print(r, residual)
r, residual = vpu.iterate(in_1)
print(r, residual)

[[0.35507246]
 [1.        ]]
[[1.02462119]] [[-0.22718288]
 [ 0.15689426]]
[[1.02462119]] [[-0.22718288]
 [ 0.15689426]]


In [11]:
for _ in range(0, 100):
    in_1 = np.random.randint(255, size=(2, 1))
    in_1 = in_1 / in_1.max()
    vpu.update_cov(in_1)
r, residual = vpu.iterate(in_1)
print(r, residual)

[[0.9990324]] [[0.16566375]
 [0.00098527]]


In [12]:
vpu.cu.covariance

array([[ 0.09394926, -0.06520071],
       [-0.06520071,  0.09860119]])

In [13]:
vpu.pi.eigenvector

array([[-0.00594728],
       [ 0.99998231]])

In [14]:
vpu.pi.cov

array([[ 0.09394926, -0.06520071],
       [-0.06520071,  0.09860119]])

In [15]:
self = vpu.pi
self.ev = np.matmul(np.power(self.cov, 1), self.ev)
# Scale to have unit length (convert to integer values?)
# self.ev = self.ev / np.linalg.norm(self.ev)
print(self.ev)

[[-0.0657583 ]
 [ 0.09898721]]


In [16]:
np.power(self.cov, 1)

array([[ 0.09394926, -0.06520071],
       [-0.06520071,  0.09860119]])

In [17]:
self.ev

array([[-0.0657583 ],
       [ 0.09898721]])

Ah this is it - if self.ev becomes nan it stays as nan. Need a check to prevent this

In [18]:
# Intialise VPU
vpu2 = VPU(2)
# Test Iteration
for _ in range(0, 100):
    data_in = np.random.randint(2, size=(2, 1))
    cause, residual = vpu2.iterate(data_in)
print(cause, residual)
print(vpu2.cu.covariance)
assert vpu2.cu.covariance.any()
assert cause.any()
assert residual.any()
vpu2.reset()
# assert not vpu2.cu.covariance.any()
print(vpu2.cu.covariance)


[[0.03363139]] [[1.02320872]
 [0.97566021]]
[[ 0.22984049 -0.03108702]
 [-0.03108702  0.23272918]]
[[0. 0.]
 [0. 0.]]


## BufferVPU

In [19]:
from src.var_processor.vpu import BufferVPU

In [20]:
vpu = BufferVPU(2, 4)
assert vpu.buffer.shape == (2, 4)
assert vpu.cu.covariance.shape == (8, 8)
assert vpu.pi.ev.shape == (8, 1)

In [23]:
reshaped = vpu.buffer.reshape(-1, 1)
print(reshaped, reshaped.shape)

[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]] (8, 1)


In [21]:
# Test Iteration
for _ in range(0, 100):
    data_in = np.random.randint(2, size=(2, 1))
    cause, residual = vpu.iterate(data_in)
old_cov = vpu.cu.covariance
assert old_cov.any()
vpu.reset()
new_cov = vpu.cu.covariance
assert not np.array_equal(old_cov, new_cov)

ValueError: non-broadcastable output operand with shape (8,1) doesn't match the broadcast shape (8,8)

# Sensor Object

The input into each VPU is a vector of N. Whatever the stage.

Class object. 
* Internal variables (for init)
    * vec_len - vector length (N)
    * time_len - length of time buffering (M)
* Methods
    * generate_stage - create a new time stage.
    * get_frame - get a frame of data from the sensor. 
        * Return:
            * frame
    


Stage.
* Internal variables (for init)
    * vec_len - vector length (N)
* Methods
    * __init__ - initialise a set of VPUs for one time stage. 
        * Input
            * stage_len - number of stages (k)
            * vec_len - vector length (N)
    * forward - input data and update VPUs.
        * Input:
            * stage_in - array of input data for stage.
        * Return:  
            * updated Rs and residuals for the stage as numpy array
    * get_cause - get the Rs from all individual VPUs. In binary form or float form?
        * Return:
            * causes - numpy array of Rs

We might actually want a "stage" object. generate_stage and process_stage are "stage" methods.

Time stages = logN(sensor_resolution)

We need a common way of getting the sensor_resolution. First time stage has sensor_resolution/N VPUs.

See:
* https://github.com/benhoyle/predictive_coding/blob/master/2019-10-28%20SpaceTime%20Grid%20object%20development.ipynb
* https://github.com/benhoyle/predictive_coding/blob/master/Time%20Filtering.ipynb

Below is very similar to our "layer" in the predictive_coding brain code. But we are flattening everything to 1D.

In [ ]:
from src.var_processor.vpu import VPU

class TimeStage:
    """Object to represent a time stage of processing."""
    
    def __init__(self, vec_len, stage_len):
        """Initialise stage.
        
        Arg:
            vec_len - length of each 1D vector processed by the VPUs.
            stage_len - integer indicating number of VPUs.
        """
        self.vec_len = vec_len
        self.stage_len = stage_len
        self.size = self.vec_len*self.stage_len
        self.vpus = [VPU(vec_len) for _ in range(0, stage_len)]
        # Create a blank array for the causes
        self.causes = np.zeros(shape=(stage_len, 1))
        # Create a blank array for the residuals
        self.residuals = np.zeros(shape=(self.size, 1))
        
    def forward(self, stage_in):
        """Pass data to the stage for processing.
        
        Arg:
            stage_in - 1D numpy array with data to process.
        """
        # Create blank array to hold / pad data
        
        input_array = np.zeros(shape=(self.size, 1))
        # Check data is of right size
        if stage_in.shape[0] > self.size:
            # Crop input
            input_array = stage_in[:self.size]
        elif stage_in.shape[0] < self.size:
            input_array[:self.size] = stage_in
        else:
            input_array = stage_in
        # Iterate through VPUs, passing data in
        # Create a blank array for the causes
        causes = np.zeros
        for i, vpu in enumerate(self.vpus):
            start = i*self.vec_len
            end = (i+1)*self.vec_len
            r, residual = vpu.iterate(input_array[start:end])
            self.causes[i] = r
            self.residuals[start:end] = residual
        
    def get_causes(self):
        """Return output of VPUs as array."""
        return self.causes
    
    def get_residuals(self):
        """Return residual output as array."""
        return self.residuals
    
    def __repr__(self):
        """Print layer information."""
        string = f"There are {self.stage_len} units \n"
        string += f"with dimensionality {self.vec_len}x1"
        return string
            
        

In [ ]:
stages = TimeStage(3, 10)
assert len(stages.vpus) == 10
assert not stages.causes.any()
assert not stages.residuals.any()
print(stages)

In [ ]:
data_in = np.random.randint(2, size=(stages.size, 1))
print(data_in.T)

stages.forward(data_in)

In [ ]:
stages.causes

In [ ]:
stages.residuals

We need a method to "bed in" the covariance - we need to input data for a certain number of iterations.

In [ ]:
"9" in stages.__repr__()

In [ ]:
for _ in range(0, 100):
    in_1 = np.random.randint(255, size=(2, 1))
    in_1 = in_1 / in_1.max()
    vpu.update_cov(in_1)

In [ ]:
class Sensor:
    """Object to process a 1D sensor signal."""

    def __init__(self, sensor_source):
        """Initialise sensor.

        Arg:
            sensor_source - SensorSource object that outputs a
            vector of sensor readings when iterated.
        """
        