In [1]:
import numpy as np
from scipy.linalg import hadamard

In [2]:
H_256 = hadamard(256)

In [3]:
H_256

array([[ 1,  1,  1, ...,  1,  1,  1],
       [ 1, -1,  1, ..., -1,  1, -1],
       [ 1,  1, -1, ...,  1, -1, -1],
       ...,
       [ 1, -1,  1, ..., -1,  1, -1],
       [ 1,  1, -1, ...,  1, -1, -1],
       [ 1, -1, -1, ..., -1, -1,  1]])

In [4]:
rand_256 = np.random.randint(2, size=(256,1))

In [6]:
rand_256.T

array([[1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0]])

In [7]:
y = np.dot(H_256, rand_256)

In [8]:
y.T

array([[119,  -9,   5,  -3,  -3,  -3,   7,  -1,  11,  -1,   1,  -3,  13,
         -7,  23, -21,  -3,  -3, -13,  11, -13,   3,  -3,   5,  13,   9,
         -5, -17,  -1,   3,   9,   5,  -1,   3,   1,  13, -15, -11,  -1,
         -5,   7,   7,   1,  -7,   5,  -3,   3,   3,  -3,  25,   7,  -5,
          7,   3,  21,  -7,   9,  -7,  -5,   3,  -1,   7,  -3,  13,   9,
         -7,  -1,  -1,  -5,  -5, -19,  -3,   5,   1,   3,  -1,   3,   7,
          5,   9,  -5,   3,   1,  -7,   5,  -3,  15,  23,  -5,   7,   9,
          5,  17,   5,  -5,  -1,   1,  -3,   3,  -1,   7,   3, -11,   1,
          1,   1,  11,  -5,   3,  -5,   1,  -7,  11,  -9,  -3,  -7,   1,
         -3,   7,   3,   7,  -1,   1,   9,  -7,  -7,  -1,  -1,   7,   3,
         -7,  -3,  17,   5,  -1,  -5,   3,   3,  -3,   5,   9,  -7, -25,
         -1,   9,  13, -13,  -1,  -5,   7,   9,  -3,   1,   1,   3,  -5,
         -1,  -1,  -3, -11,  -5,   3,  -7,  -7,   1, -15,  -5, -13,  -5,
         -1,   1,  -3,  13, -15,  -9,   3,  -3, -11

In [9]:
def pair_transform(vec1, vec2):
    """Apply the H_2 transform."""
    y_1 = vec1 + vec2
    y_2 = vec1 - vec2
    return np.concatenate([y_1, y_2])

In [12]:
pair_transform(rand_256[0:2], rand_256[2:4])

array([[2],
       [2],
       [0],
       [0]])

Shape = (4, 1)

In [14]:
segments = np.split(rand_256, rand_256.shape[0]/2)
print(len(segments), segments[0])

128 [[1]
 [1]]


In [ ]:
# segments = np.split(input_vector, length/2)

def recursive_transform(input_vector):
    """Recursively apply a Hadamard tranform."""
    # Split input into 2
    length = input_vector.shape[0]
    if length > 2:
        transformed = recursive_transform(input_vector[0:length/2])
    else:
        transformed = pair_transform(input_vector[:1], input_vector[1:])
    # If input length is 2
    ## return Transform(split_input)
    # Else
    ## Recursion
    pass

def iterative_transform(pair_list):
    """Iteratively apply a Hadamard tranform."""
    running_transform = None
    for segment in segments:
        transformed = pair_transform(segment[:1], segment[1:])
        if running_transform in not None:
            running_transform
