# Matrix Factorisation

In this short post, we'll look at how we can factorise a matrix transform.

As a matrix multiplication is a linear transformation, we can decompose it into a series of separate smaller multiplications.

In [1]:
import numpy as np

In [2]:
# Generate random 8 by 8 matrix
rand_mat = np.random.randint(255, size=(8, 8))
print(rand_mat)

[[118 110  51 202  31  86 194 131]
 [ 96  87 182  40 108  49   4 203]
 [151 190 101 118 131  27 202 102]
 [158  41  28  51 145 203 227 198]
 [ 32 167  95 223  65 170  57  24]
 [ 55 102 160 179  72 181  71 208]
 [ 64   7  55  13  37 197  55 121]
 [243  10  11 247  16 234  15 108]]


In [7]:
# Function to partition a matrix by reshaping and swapping axes
def partition_matrix(matrix, vec_len):
    """Partition a matrix to clustered blocks of size vec_len^2."""
    rows = matrix.shape[0] // vec_len
    cols = matrix.shape[1] // vec_len
    return matrix.reshape(rows, vec_len, cols, vec_len).swapaxes(2, 1)

In [8]:
# Partition into 16 2x2 matrices
partitioned = partition_matrix(rand_mat, 2); print(partitioned)

[[[[118 110]
   [ 96  87]]

  [[ 51 202]
   [182  40]]

  [[ 31  86]
   [108  49]]

  [[194 131]
   [  4 203]]]


 [[[151 190]
   [158  41]]

  [[101 118]
   [ 28  51]]

  [[131  27]
   [145 203]]

  [[202 102]
   [227 198]]]


 [[[ 32 167]
   [ 55 102]]

  [[ 95 223]
   [160 179]]

  [[ 65 170]
   [ 72 181]]

  [[ 57  24]
   [ 71 208]]]


 [[[ 64   7]
   [243  10]]

  [[ 55  13]
   [ 11 247]]

  [[ 37 197]
   [ 16 234]]

  [[ 55 121]
   [ 15 108]]]]


In [9]:
# So we have a 4x4 matrix of 2x2 matrices
partitioned.shape

(4, 4, 2, 2)

In [13]:
# Generate an X vector of length 8
X = np.random.randint(255, size=(8, 1)); print(X)

[[226]
 [ 26]
 [ 21]
 [219]
 [103]
 [153]
 [144]
 [164]]


In [15]:
# Determine M*X
product = np.dot(rand_mat, X); print(product)

[[140608]
 [ 89029]
 [130469]
 [159685]
 [107255]
 [137088]
 [ 80364]
 [166824]]


In [32]:
first_sum = np.zeros(shape=(2, 1))
for i in range(4):
    sub_M = partitioned[1, i, :, :]
    sub_X = X[2*i:2*i+2]
    product = np.dot(sub_M, sub_X)
    first_sum += product
    print(sub_M, sub_X, product, sep="\n", end="\n\n")
print(first_sum)

[[151 190]
 [158  41]]
[[226]
 [ 26]]
[[39066]
 [36774]]

[[101 118]
 [ 28  51]]
[[ 21]
 [219]]
[[27963]
 [11757]]

[[131  27]
 [145 203]]
[[103]
 [153]]
[[17624]
 [45994]]

[[202 102]
 [227 198]]
[[144]
 [164]]
[[45816]
 [65160]]

[[130469.]
 [159685.]]


In [23]:
partitioned[0, 0, :, :]

array([[118, 110],
       [ 96,  87]])

In [24]:
X[0:2]

array([[226],
       [ 26]])

In [25]:
np.dot(sub_M, X[0:2])

array([[47250],
       [ 6182]])

In [26]:
partitioned[0, 1, :, :]

array([[ 51, 202],
       [182,  40]])